services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=music_reviews'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'
#     volumes:
#       - data:/var/lib/postgresql/data
# volumes:
#   data: