version: '3'
services:
  app:
    container_name: music_reviews_app
    build: .
    ports:
      - "8080:8080"
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres-container:5432/music_reviews
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-container:5432/music_reviews
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db
    networks:
      - internal
  db:
    container_name: postgres-container
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=music_reviews'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - internal
volumes:
  data:
networks:
  internal: